# Generated by Django 6.0 on 2025-12-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
    ]
