# Generated by Django 6.0 on 2025-12-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
    ]
