# Generated by Django 6.0 on 2025-12-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('percentage', models.IntegerField(verbose_name='درصد')),
            ],
            options={
                'verbose_name': 'مهارت شخصی',
                'verbose_name_plural': 'مهارت های شخصی',
            },
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'تحصیل', 'verbose_name_plural': 'تحصیلات'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'تجربه', 'verbose_name_plural': 'تجربیات'},
        ),
        migrations.AlterField(
            model_name='education',
            name='body',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='education',
            name='time',
            field=models.CharField(max_length=100, verbose_name='بازه زمانی'),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(max_length=100, verbose_name='دانشگاه'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='body',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=100, verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='field',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='time',
            field=models.CharField(max_length=100, verbose_name='بازه زمانی'),
        ),
    ]
