# Generated by Django 6.0 on 2025-12-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_skill_alter_education_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('percentage', models.IntegerField(verbose_name='درصد')),
            ],
            options={
                'verbose_name': 'مهارت نرم افزاری',
                'verbose_name_plural': 'مهارت های نرم افزاری',
            },
        ),
    ]
