# Generated by Django 6.0 on 2025-12-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='service/icons')),
                ('name', models.CharField(max_length=100)),
                ('short', models.TextField()),
                ('img', models.ImageField(upload_to='service/img')),
                ('body', models.TextField()),
            ],
        ),
    ]
