# Generated by Django 6.0 on 2025-12-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'خدمت', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.AlterField(
            model_name='service',
            name='body',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(upload_to='service/icons', verbose_name='ایکون'),
        ),
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.ImageField(upload_to='service/img', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short',
            field=models.TextField(verbose_name='کوتاه'),
        ),
    ]
