# Generated by Django 6.0 on 2025-12-31 13:17

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'شخص', 'verbose_name_plural': 'اشخاص'},
        ),
        migrations.AlterField(
            model_name='person',
            name='Nationality',
            field=models.CharField(max_length=100, verbose_name='ملیت'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=100, verbose_name='ادرس'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=django_jalali.db.models.jDateField(verbose_name='روز تولد'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='person',
            name='experience',
            field=models.CharField(max_length=100, verbose_name='سال های تجربه'),
        ),
        migrations.AlterField(
            model_name='person',
            name='facebook',
            field=models.URLField(verbose_name='فیسبوک'),
        ),
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(upload_to='img/person/', verbose_name='عکس سایت'),
        ),
        migrations.AlterField(
            model_name='person',
            name='instagram',
            field=models.URLField(verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='person',
            name='job',
            field=models.CharField(max_length=100, verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='person',
            name='resume',
            field=models.FileField(upload_to='file/resume/', verbose_name='رزومه'),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.URLField(verbose_name='توییتر'),
        ),
        migrations.AlterField(
            model_name='person',
            name='youtube',
            field=models.URLField(verbose_name='یوتیوب'),
        ),
    ]
