# Generated by Django 6.0 on 2025-12-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('job', models.CharField(max_length=100, verbose_name='شغل')),
                ('img', models.ImageField(upload_to='images/customer/', verbose_name='عکس')),
                ('body', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
    ]
